# Generated by Django 4.0.4 on 2022-05-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=200)),
                ('registro_cadastro', models.DateTimeField(auto_now_add=True)),
                ('registro_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'produto',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('data_nascimento', models.DateField()),
                ('ddd', models.CharField(max_length=3)),
                ('telefone', models.CharField(max_length=10)),
                ('registro_cadastro', models.DateTimeField(auto_now_add=True)),
                ('registro_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('produtos_cadastrados', models.ManyToManyField(default='Não contratou nenhum serviço', to='costumer.produto')),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
    ]
